import { SectionTypes } from "./section-types.enum";

export const sectionTypesToLabelsMap: Map<number, string> = new Map<number, string>([
  [ SectionTypes.NONE, 'None' ],
  [ SectionTypes.AREA, 'Area' ],
  [ SectionTypes.AUDITING, 'Audit Trail' ],
  [ SectionTypes.CALENDAR, 'Calendar' ],
  [ SectionTypes.CATEGORY, 'Category' ],
  [ SectionTypes.CERTIFICATE_TYPE, 'Certificate Type' ],
  [ SectionTypes.CREATE_ACTIVE_PROCEDURE, 'Create Active Procedure' ],
  [ SectionTypes.CREATE_NOTE, 'Create Note' ],
  [ SectionTypes.CREATE_PURCHASE_ORDER, 'Create Purchase Order' ],
  [ SectionTypes.CREATE_WORK_ORDER, 'CREATE Work Order' ],
  [ SectionTypes.CRITICALITY_RANKING, 'Work Criticality Ranking' ],
  [ SectionTypes.CUSTOM_FIELDS, 'Custom Fields' ],
  [ SectionTypes.DASHBOARD, 'Dashboard' ],
  [ SectionTypes.DEPARTMENT, 'Department' ],
  [ SectionTypes.DOCUMENT, 'Document' ],
  [ SectionTypes.DRAG_VIEW, 'Drag View' ],
  [ SectionTypes.ENTER_READINGS, 'Enter Readings' ],
  [ SectionTypes.EQUIPMENT, 'Equipment' ],
  [ SectionTypes.EQUIPMENT_PRIORITY, 'Equipment Priority' ],
  [ SectionTypes.EQUIPMENT_CONDITION, 'Equipment Condition' ],
  [ SectionTypes.EQUIPMENT_TYPE, 'Equipment Type' ],
  [ SectionTypes.GROUP, 'Group' ],
  [ SectionTypes.HOME, 'Home' ],
  [ SectionTypes.INSTRUMENT, 'Instrument' ],
  [ SectionTypes.LABOR_ACCOUNT, 'Labor Account' ],
  [ SectionTypes.LABOR_CLASS, 'Labor Class' ],
  [ SectionTypes.LABOR_TYPE, 'Labor Type' ],
  [ SectionTypes.LOCATION, 'Location' ],
  [ SectionTypes.ADDRESS, 'Mailing Address' ],
  [ SectionTypes.MAINTENANCE_GROUP, 'Maintenance Group' ],
  [ SectionTypes.MANUFACTURER, 'Manufacturer' ],
  [ SectionTypes.MAPPING, 'Mapping' ],
  [ SectionTypes.MEMORIZED_REPORT, 'Memorized Report' ],
  [ SectionTypes.MEMORIZED_REPORT_GROUP, 'Memorized Report Group' ],
  [ SectionTypes.MY_WORK, 'My Work' ],
  [ SectionTypes.NOTE, 'Notes' ],
  [ SectionTypes.OPTION, 'Option' ],
  [ SectionTypes.ORDER_HISTORY, 'Order History' ],
  [ SectionTypes.PART, 'Part' ],
  [ SectionTypes.PARTS_AUDIT, 'Parts Audit' ],
  [ SectionTypes.ORDERING, 'Parts Ordering' ],
  [ SectionTypes.PARTS_RECEIVING, 'Parts Receiving' ],
  [ SectionTypes.PARTS_REORDER, 'Parts Reorder' ],
  [ SectionTypes.PART_STOCK, 'Part Stock' ],
  [ SectionTypes.PARTS_USAGE, 'Parts Usage' ],
  [ SectionTypes.PARTS_TRANSFER, 'Parts Transfer' ],
  [ SectionTypes.PROCEDURES, 'Procedures' ],
  [ SectionTypes.PROCEDURE_SETUP, 'Procedures Setup' ],
  [ SectionTypes.PROCEDURES_HISTORY, 'Procedures History' ],
  [ SectionTypes.PRODUCT_GROUP, 'Product Group' ],
  [ SectionTypes.PRODUCT_TYPE, 'Product Type' ],
  [ SectionTypes.REPORT_CENTER, 'Report Center' ],
  [ SectionTypes.REPORTING, 'Reporting' ],
  [ SectionTypes.SEAT, 'Seat' ],
  [ SectionTypes.SECURITY, 'Security' ],
  [ SectionTypes.STANDARD_FORMS, 'Standard Forms' ],
  [ SectionTypes.STOCK_LOCATION, 'Stock Location' ],
  [ SectionTypes.SUBLOCATION, 'Sub-location' ],
  [ SectionTypes.SUPPLIER, 'Supplier' ],
  [ SectionTypes.TASK, 'Task' ],
  [ SectionTypes.TRANSACTIONS, 'Transactions' ],
  [ SectionTypes.USER, 'User' ],
  [ SectionTypes.USER_CERTIFICATE, 'User Certificate' ],
  [ SectionTypes.VENDOR, 'Vendor' ],
  [ SectionTypes.WAREHOUSE, 'Warehouse' ],
  [ SectionTypes.WORK_MANAGEMENT, 'Work Management' ],
  [ SectionTypes.WORK_HISTORY, 'Work History' ],
  [ SectionTypes.WORK_ORDER_VIEWER, 'Work Order Viewer' ],
  [ SectionTypes.WORK_PRIORITY, 'Work Priority' ],
  [ SectionTypes.WORK_REVIEW, 'Work Review' ],
  [ SectionTypes.WORK_TYPE, 'Work Type' ],
  [ SectionTypes.WORK_REQUEST, 'Work Request' ],
  [ SectionTypes.WORK_STATUS, 'Work Status' ],
  [ SectionTypes.WORK_TEMPLATES, 'Work Templates' ],
  [ SectionTypes.INVENTORY_ADJUSTMENT, 'Inventory Adjustment' ]
]);