export enum UserDataCategories {
  NONE = 0,
  GRID_LAYOUT,
  MAPPING,
  SPLITTER_POSITION,
  SYSTEM,
  GRID_PANEL_WIDTH,
  QAT_LAYOUT,
  DETAIL_VISIBLE,
  STARTUP_SECTION,
  SHOW_GROUP_PANEL,
  SHOW_WORK_ORDER_MOVE_TO_REVIEW_PROMPT,
  SHOW_WORK_ORDER_MOVE_TO_HISTORY_PROMPT,
  CALENDAR_SETTINGS,
  GRID_PANEL_HEIGHT,
  DASHBOARD_LAYOUT
}